matrix:
  include:
  - name: csharp
    os: linux
    dist: bionic
    language: csharp
    dotnet: 2.1.700
    mono: none

    env:
      global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

    before_script:
      - chmod a+x ./build.sh

    script:
      - ./build.sh
